import type { HealthResponse, HelloResponse } from '@finai/shared';
import { useQuery } from '@tanstack/react-query';

import { apiFetch } from '../api/client.js';
import { Shell } from '../components/Shell.js';

/**
 * Scaffold landing page. Renders the greeting produced by the API so a
 * deployed container visibly proves the web -> API wiring.
 */
export function HomePage() {
  const hello = useQuery({
    queryKey: ['hello'],
    queryFn: () => apiFetch<HelloResponse>('/hello'),
  });

  const health = useQuery({
    queryKey: ['health'],
    queryFn: () => apiFetch<HealthResponse>('/health'),
  });

  const state = hello.isPending ? 'pending' : hello.isError ? 'error' : 'ok';

  return (
    <Shell>
      <h1 className="title">System check</h1>
      <p className="dim">
        The value below is generated by the API and rendered by the web client. If it moves when you
        refresh, the container is wired end to end.
      </p>

      <section className="panel" style={{ marginTop: '2rem' }}>
        <div className="panel__head">
          <span className="status">
            <span className={`status__dot status__dot--${state}`} />
            <span className="label">GET /api/hello</span>
          </span>
          <button
            type="button"
            className="button"
            onClick={() => void hello.refetch()}
            disabled={hello.isFetching}
          >
            {hello.isFetching ? 'fetching' : 'refresh'}
          </button>
        </div>

        <div className="panel__body">
          {hello.isPending && <p className="readout readout--pending">awaiting response…</p>}

          {hello.isError && <p className="readout readout--error">{hello.error.message}</p>}

          {hello.data && (
            <p className="readout">
              {hello.data.message} at {new Date(hello.data.time).toLocaleString()}
            </p>
          )}
        </div>
      </section>

      <div className="rows">
        <div className="row">
          <span className="label">server version</span>
          <span className="mono dim">{health.data?.version ?? '—'}</span>
        </div>
        <div className="row">
          <span className="label">uptime</span>
          <span className="mono dim">{health.data ? `${health.data.uptimeSeconds}s` : '—'}</span>
        </div>
        <div className="row">
          <span className="label">raw timestamp</span>
          <span className="mono dim">{hello.data?.time ?? '—'}</span>
        </div>
      </div>
    </Shell>
  );
}
